# Site settings
title: "Carrot Land"
email: caiborong@gmail.com
description: "A carrot's lonely space."
baseurl: ""
url: "https://carrot.dev/"
title_description: "If not now, when?"
title_image: "https://img.nga.178.com/avatars/2002/8b2/145/000/1333426_0.jpg"
google_analytics: "UA-20365477-4"
disqus_account: carroTsai
github_repository: https://github.com/carroTsai/carrotsai.github.io
addthis_id: ra-513c6fa83da6ec67
post_limit: 5

# Social usernames/URLs
twitter_username: caiborong
github_username:  carroTsai
instagram_username: carrotsai
reddit_username: carrotsai

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
