# Site settings
title: "Carrot Tsai"
email: caiborong@gmail.com
description: "A carrot's lonely space."
baseurl: ""
url: "https://carrot.dev/"
title_description: "If not now, when?"
title_image: "http://www.yulu1.com/uploadfile/2015/0725/20150725061626737.jpg"
google_analytics: "UA-20365477-4"
disqus_account: carroTsai
github_repository: https://github.com/carroTsai/carrotsai.github.io
addthis_id: ra-513c6fa83da6ec67
post_limit: 5

# Social usernames/URLs
twitter_username: caiborong
github_username:  carroTsai
instagram_username: carrotsai
reddit_username: carrotsai

# Footer
footer_left: "Made with <i class=\"fa fa-heart\"></i> by <a href=\"https://twitter.com/_JacobTomlinson\">Jacob Tomlinson</a>"
footer_right: "&lt;/&gt; on <a href=\"https://github.com/jacobtomlinson/carte-noire\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
